### ISSUE TITLE
Facebook login required?

### ISSUE THREAD

**Issue by henriquelbsouza** [sonvq/socialAutoPostingPHP#1]
Hi, I am trying to use the facebookapi for some tests and when I try to register a facebook app on facebook.com he asks for login and informations about how it will be used etc...

Is there anything I can do to don't need this? (I will use to autopost some blog posts at my facebook group)

**Comment by sonvq** [comment]
Hi, To autopost your blog posts at your facebook group, you have to:
1. Register for a facebook app at https://developers.facebook.com/
2. After registering for app, you get App ID and App Secret
3. Use Access Token tool at https://developers.facebook.com/tools/accesstoken/ to get your long live access token that is authorized for post on fb group
4. Find your facebook group id with this page: https://lookup-id.com/
5. Run a test with this find socialAutoPostingPHP/facebookapi/facebookStatus.php | Remember to replace you correct app id, app secret, access token and facebook group id
6. You are done ;)
If you have further questions, you can contact me via skype: langtutuoiteen5011
